# Generated by Django 2.2.2 on 2019-07-17 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0005_descuentotarifa_planpago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuentotarifa',
            name='plan_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='parqueaderos.PlanPago'),
        ),
    ]
