# Generated by Django 2.2.2 on 2019-07-18 04:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190703_1725'),
        ('parqueaderos', '0006_auto_20190717_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parqueadero',
            fields=[
                ('nombre', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(25)])),
                ('direccion', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(25)])),
                ('telefono', models.PositiveIntegerField(max_length=10, validators=[django.core.validators.MaxLengthValidator(25)])),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Usuario')),
            ],
        ),
    ]
