# Generated by Django 2.2.2 on 2019-07-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0006_auto_20190717_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradavehiculo',
            name='usuario',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
