# Generated by Django 2.2.2 on 2019-07-24 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0007_entradavehiculo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradavehiculo',
            name='tarifa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarifa', to='parqueaderos.Tarifa'),
        ),
    ]
