# Generated by Django 2.2.2 on 2019-07-18 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0007_parqueadero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parqueadero',
            name='telefono',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
