# Generated by Django 2.2.2 on 2019-07-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0009_auto_20190724_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradavehiculo',
            name='telefono_parq',
            field=models.PositiveIntegerField(default=573820),
        ),
    ]
