# Generated by Django 2.2.2 on 2019-07-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0011_auto_20190724_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradavehiculo',
            name='direccion_parq',
            field=models.CharField(default='Cl 49 55-77', max_length=50),
        ),
    ]
