# Generated by Django 2.2.2 on 2019-07-24 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0012_auto_20190724_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entradavehiculo',
            old_name='direccion_parq',
            new_name='dir_parq',
        ),
        migrations.RenameField(
            model_name='entradavehiculo',
            old_name='nombre_parq',
            new_name='nom_parq',
        ),
        migrations.RenameField(
            model_name='entradavehiculo',
            old_name='telefono_parq',
            new_name='tel_parq',
        ),
    ]
