# Generated by Django 2.2.2 on 2019-07-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0013_auto_20190724_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradavehiculo',
            name='dir_parq',
            field=models.CharField(default='Cl 49 55-77', max_length=80),
        ),
        migrations.AlterField(
            model_name='entradavehiculo',
            name='nom_parq',
            field=models.CharField(default='Estacionamiento Ayacucho', max_length=80),
        ),
    ]
