# Generated by Django 2.2.2 on 2019-07-24 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0014_auto_20190724_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradavehiculo',
            name='nom_parq',
        ),
    ]
