# Generated by Django 2.2.2 on 2019-07-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0017_auto_20190724_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradavehiculo',
            name='dir_parq',
            field=models.CharField(default='Cra 15 #17-22', max_length=80),
        ),
        migrations.AlterField(
            model_name='entradavehiculo',
            name='nom_parq',
            field=models.CharField(default='Parqueadero Laureles', max_length=80),
        ),
        migrations.AlterField(
            model_name='entradavehiculo',
            name='tel_parq',
            field=models.PositiveIntegerField(default=5473322),
        ),
    ]
