# Generated by Django 2.2.2 on 2019-07-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0018_auto_20190724_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradavehiculo',
            name='tel_parq',
            field=models.BigIntegerField(default=5473322),
        ),
    ]
