# Generated by Django 2.2.2 on 2019-07-26 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0008_remove_parqueadero_eliminado'),
        ('parqueaderos', '0019_auto_20190724_1742'),
    ]

    operations = [
    ]
