# Generated by Django 2.2.2 on 2019-07-26 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0020_merge_20190726_1759'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planpago',
            options={'ordering': ['-creado'], 'verbose_name': 'plan de pago'},
        ),
        migrations.AddField(
            model_name='entradavehiculo',
            name='parqueadero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parq', to='parqueaderos.Parqueadero'),
        ),
    ]
