# Generated by Django 2.2.2 on 2019-07-27 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0021_auto_20190726_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradavehiculo',
            name='dir_parq',
        ),
        migrations.RemoveField(
            model_name='entradavehiculo',
            name='nom_parq',
        ),
        migrations.RemoveField(
            model_name='entradavehiculo',
            name='tel_parq',
        ),
    ]
