# Generated by Django 2.1.1 on 2019-07-30 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190730_1844'),
        ('vehiculos', '0007_remove_vehiculo_tarifa'),
        ('parqueaderos', '0022_auto_20190726_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaVehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20)),
                ('fecha_salida', models.DateTimeField(auto_now_add=True)),
                ('entrada_vehiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parqueaderos.EntradaVehiculo')),
                ('operario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Usuario')),
                ('tipo_vehiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiculos.Vehiculo')),
            ],
        ),
    ]
