# Generated by Django 2.1.1 on 2019-07-31 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0023_salidavehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidavehiculo',
            name='tipo_vehiculo',
            field=models.CharField(default='nada', max_length=10),
            preserve_default=False,
        ),
    ]
