# Generated by Django 2.1.1 on 2019-08-01 03:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0025_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(25)]),
        ),
    ]
