# Generated by Django 2.2.2 on 2019-08-02 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0027_factura_tipo_vehiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['-out_date'], 'verbose_name': 'ver factura'},
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='name',
            new_name='namePA',
        ),
        migrations.AddField(
            model_name='factura',
            name='nameOP',
            field=models.CharField(default='no tiene', max_length=25, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(25)]),
            preserve_default=False,
        ),
    ]
