# Generated by Django 2.2.2 on 2019-08-02 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0028_auto_20190802_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='namePA',
            new_name='name',
        ),
    ]
