# Generated by Django 2.2.2 on 2019-08-05 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0030_entradavehiculo_estado_facturado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteFrecuente',
            fields=[
                ('identificacion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('numero_celular', models.BigIntegerField()),
                ('email', models.EmailField(max_length=40, null=True)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('plan_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parqueaderos.PlanPago')),
            ],
        ),
    ]
