# Generated by Django 2.2.2 on 2019-08-08 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0030_entradavehiculo_estado_facturado'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradavehiculo',
            name='identificacion',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
