# Generated by Django 2.2.2 on 2019-08-14 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0031_planpago_identificacion'),
        ('parqueaderos', '0031_entradavehiculo_identificacion'),
    ]

    operations = [
    ]
