# Generated by Django 2.2.2 on 2019-08-14 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0032_merge_20190813_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planpago',
            name='identificacion',
        ),
    ]
