# Generated by Django 2.2.2 on 2019-08-14 16:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0034_auto_20190814_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='descuento',
            field=models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
