# Generated by Django 2.2.2 on 2019-08-15 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderos', '0035_auto_20190814_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='total_general',
            field=models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
