# Generated by Django 2.2.2 on 2019-07-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_auto_20190709_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='tarifa',
            field=models.PositiveIntegerField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
