# Generated by Django 2.2.2 on 2019-07-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_auto_20190709_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='tarifa',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
