# Generated by Django 2.2.2 on 2019-08-15 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0008_vehiculoclientefrecuente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculoclientefrecuente',
            options={'verbose_name': 'vehiculos_clientes'},
        ),
    ]
