# Generated by Django 2.2.2 on 2019-07-04 06:36

from django.db import migrations, models
import django.db.models.deletion
import vehiculos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parqueaderos', '0004_auto_20190702_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(max_length=10)),
                ('anno', models.PositiveIntegerField(default=vehiculos.models.current_year, verbose_name='año')),
                ('tarifa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parqueaderos.Tarifa')),
            ],
        ),
    ]
